config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :departments do
  	resources :reviews
  end
  resources :categories
  root 'departments#home'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :departments
	belongs_to :users
end

app/models/department.rb
class Department < ActiveRecord::Base
	belongs_to :user
	belongs_to :category
	has_many :reviews

	has_attached_file :department_img, :styles => { :department_index => "250x350>", :department_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :department_img, :content_type => /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :department
	belongs_to :usr
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :departments
	has_many :categories
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

def new
	@category = current_user.categories.build
end

def create
	@category = current_user.categories.build(category_params)

	if @category.save
		redirect_to root_path
	else
		render 'categories#new'
	end
end

def category_params
	params.require(:category).permit(:name)
end

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
	before_action :find_department, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		if params[:category].blank?
			@departments = Department.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@departments = Department.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		#if @department.reviews.blank?
		#	@average_review = 0
		#else
			#@average_review = @department.reviews.average(:rating).round(2)
		#end
	end

	def new
		@department = current_user.departments.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@department = current_user.departments.build(department_params)
		@department.category_id = params[:category_id]

		if @department.save
			redirect_to root_path
		else
			@categories = Category.all.map{ |c| [c.name, c.id] }
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		@department.category_id = params[:category_id]
		if @department.update(department_params)
			redirect_to department_path(@department)
		else
			render 'edit'
		end
	end

	def destroy
		@department.destroy
		redirect_to root_path
	end

	private

		def department_params
			params.require(:department).permit(:title, :description, :author, :category_id, :department_img)
		end

		def find_department
			@department = Department.find(params[:id])
		end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_department
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.department_id = @department.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to department_path(@department)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to department_path(@department)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to department_path(@department)
	end

	private

		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_department
			@department = Department.find(params[:department_id])
		end

		def find_review
			@review = Review.find(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => { :multipart => true } do |f| %>
	<%= f.input :name, label: "Constituency" %>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/categories/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">

		<h1>New Constituency</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/departments/_form.html.erb
<%= simple_form_for @department, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Constituency") %>
	<%= f.file_field :department_img %>
	<%= f.input :title, label: "Politician" %>
	<%= f.input :description %>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/departments/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-department-form">

		<h1>Edit Politician</h1>

		<%= simple_form_for @department, :html => { :multipart => true } do |f| %>
			<%= f.select :category_id, @categories %>
			<%= f.file_field :department_img %>
			<%= f.input :title, label: "Politician" %>
			<%= f.input :description %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>

	</div>

</div>

app/views/departments/home.html.erb
<h1>Please choose a constituency.</h1>

app/views/departments/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @departments.count == 0 %>

	<h1>There are no Politicians currently in this constituency.</h1>

<% else %>	

	<div class="row">

		<% @departments.each do |department| %>

			<div class="col-md-3">
				<a href="/departments/<%= department.id %>">
					<%= image_tag department.department_img.url(:department_index), class: "department" %>
					<%= department.title %>
				</a>
			</div>	

		<% end %>

	</div>
	
<% end %>	

app/views/departments/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">

		<h1>New Politicians</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/departments/show.html.erb
<div class="row">

	<div class="col-md-4">

		<%= image_tag @department.department_img.url(:department_show), class: "department-show" %>

	</div>

	<div class="col-md-8">

		<div class="department-info">

			<h2 class="department-title"><%= @department.title %></h2>
			<p class="department-desc"><%= @department.description %></p>
			<div class="col-md-4">

		<div class="reviews">

			<!-- Where the reviews/ratings will go -->
			<h1>Reviews</h1>
			<%= render @department.reviews %>

			<div>
				<%= link_to "Add Review", new_department_review_path(@department), class: "btn-custom" %>
			</div>

		</div>
		</div>
	</div>


</div>



<div class="links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>

	<% if user_signed_in? %>

		<% if @department.user_id == current_user.id %>

			<%= link_to "Edit", edit_department_path(@department), class: "btn btn-custom" %>
			<%= link_to "Delete", department_path(@department), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

		<% end %>

	<% end %>	

</div>	


<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>


<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Government Feedback</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">

		<div class="container">

			<div class="navbar-header">
				<%= link_to "Politician Review", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>

			<ul class="nav navbar-nav navbar-right">

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Constituency <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								
								<%= link_to category.name, departments_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>


				
				
			</ul>

		</div>

	</nav>

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
		<%= yield %>
	</div>	

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@department, @department.reviews.build]) do |f| %>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">

	<p class="review-comment"><%= review.comment %></p>


	<% if user_signed_in? %>

		<% if review.user_id == current_user.id %>

			<div class="links btn-group">

				<%= link_to "Edit", edit_department_review_path(review.department, review), class: "btn btn-custom" %>
				<%= link_to "Delete", department_review_path(review.department, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

			</div>
		
		<% end %>	

	<% end %>

</div>		

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		<h1>Edit Review</h1>

		<%= simple_form_for([@department, @review]) do |f| %>
			<div id="rating-form">
				<label>Rating</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>	

	</div>

</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

		<h1>New Review</h1>

		<%= render 'form' %>

	</div>

</div>